import pyautogui, mouseinfo, time
mouseinfo.mouseInfo()
pyautogui.moveTo(772,1062, duration=1)
pyautogui.click()
pyautogui.write("opera gx")
pyautogui.moveTo(845,431, duration=1)
pyautogui.click()
pyautogui.moveTo(88,27, duration=1)
pyautogui.click()
pyautogui.moveTo(984,146, duration=3)
pyautogui.click()
pyautogui.write("sonic youth 100 percent tab")
pyautogui.press("Enter")
pyautogui.moveTo(526,296, duration=3)
pyautogui.click()
pyautogui.moveTo(506,1012, duration=2)
pyautogui.click()
pyautogui.moveTo(420,998, duration=2)
pyautogui.click()